import logging
from typing import List, Dict, Any, Optional, Callable

# Assuming core components are defined elsewhere, e.g., in core/task.py
# For this file, we define minimal necessary structures if they are not imported.
class PlanStep:
    """Represents a single step in the research plan."""
    def __init__(self, step_id: str, description: str, dependencies: List[str], tool_call: Optional[str] = None):
        self.step_id = step_id
        self.description = description
        self.dependencies = dependencies
        self.tool_call = tool_call

    def __repr__(self):
        return f"Step({self.step_id}: {self.description[:30]}...)"

class ResearchPlan:
    """Represents the complete plan generated by the planner."""
    def __init__(self, initial_query: str, steps: List[PlanStep], strategy: str = "Sequential"):
        self.initial_query = initial_query
        self.steps = steps
        self.strategy = strategy
        self.status = "Draft"

    def __repr__(self):
        return f"Plan(Query='{self.initial_query[:20]}...', Steps={len(self.steps)}, Strategy={self.strategy})"

# Setup basic logging
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

class QueryPlanner:
    """
    Handles the decomposition and scheduling of a high-level research query
    into an executable sequence of steps (the ResearchPlan).

    This module embodies the 'Query Planning' component of the system.
    It leverages LLMs (simulated here) to generate plans based on defined strategies.
    """
    def __init__(self, llm_interface: Any, strategy_registry: Optional[Dict[str, Callable]] = None):
        """
        Initializes the QueryPlanner.

        Args:
            llm_interface: An object capable of interfacing with the underlying LLM (e.g., an LLMClient).
            strategy_registry: A dictionary mapping strategy names to planning functions.
        """
        self.llm_interface = llm_interface
        self.strategy_registry = strategy_registry if strategy_registry is not None else {
            "sequential": self._default_sequential_planner,
            "parallel": self._default_parallel_planner,
            "tree_based": self._default_tree_based_planner,
        }
        logger.info("QueryPlanner initialized.")

    def generate_plan(self, query: str, strategy: str = "sequential", context: Optional[Dict[str, Any]] = None) -> ResearchPlan:
        """
        Generates a detailed research plan from a high-level query.

        Args:
            query: The initial research question or goal.
            strategy: The planning paradigm to use (e.g., 'sequential', 'tree_based').
            context: Optional context data (e.g., previous results, constraints).

        Returns:
            A ResearchPlan object detailing the steps.

        Raises:
            ValueError: If the requested strategy is not registered.
        """
        if strategy not in self.strategy_registry:
            raise ValueError(f"Unknown planning strategy: {strategy}. Available: {list(self.strategy_registry.keys())}")

        logger.info(f"Generating plan for query: '{query[:50]}...' using strategy: {strategy}")

        # 1. Use LLM to generate a raw plan structure based on the strategy
        # In a real system, this would involve complex prompting.
        try:
            raw_plan_data = self._invoke_llm_for_planning(query, strategy, context)
        except Exception as e:
            logger.error(f"LLM invocation failed during planning: {e}")
            # Fallback to a simple default plan if LLM fails
            return self._default_sequential_planner(query, context)

        # 2. Parse and validate the raw data into the structured ResearchPlan object
        plan = self._parse_and_validate_plan(raw_plan_data, query, strategy)

        logger.info(f"Plan generated successfully with {len(plan.steps)} steps.")
        return plan

    def _invoke_llm_for_planning(self, query: str, strategy: str, context: Optional[Dict[str, Any]]) -> Dict[str, Any]:
        """
        Simulates calling the LLM API to generate the plan structure.
        This function is where prompt engineering for planning resides.
        """
        # Placeholder for actual LLM call (e.g., self.llm_interface.generate_structured_output)
        
        # Mock response structure based on strategy
        if strategy == "sequential":
            return {
                "strategy": "Sequential",
                "steps": [
                    {"id": "S1", "desc": "Initial literature search on the core topic.", "deps": []},
                    {"id": "S2", "desc": "Analyze top 5 retrieved documents for key concepts.", "deps": ["S1"]},
                    {"id": "S3", "desc": "Formulate sub-questions based on analysis.", "deps": ["S2"]},
                ]
            }
        elif strategy == "tree_based":
            return {
                "strategy": "Tree-based Planning",
                "steps": [
                    {"id": "T1", "desc": "Decompose query into 3 main branches.", "deps": []},
                    {"id": "T2", "desc": "Execute branch A research.", "deps": ["T1"]},
                    {"id": "T3", "desc": "Execute branch B research.", "deps": ["T1"]},
                    {"id": "T4", "desc": "Synthesize results from T2 and T3.", "deps": ["T2", "T3"]},
                ]
            }
        else:
            # Default fallback structure if LLM returns something unexpected
            return {"strategy": strategy, "steps": []}


    def _parse_and_validate_plan(self, raw_data: Dict[str, Any], query: str, strategy: str) -> ResearchPlan:
        """Converts raw dictionary output into a structured ResearchPlan."""
        steps: List[PlanStep] = []
        
        if not raw_data.get("steps"):
            logger.warning("LLM returned an empty step list. Using default fallback.")
            return self._default_sequential_planner(query, None)

        for item in raw_data["steps"]:
            try:
                step = PlanStep(
                    step_id=str(item["id"]),
                    description=str(item["desc"]),
                    dependencies=item.get("deps", []),
                    tool_call=item.get("tool") # Optional tool hint
                )
                steps.append(step)
            except Exception as e:
                logger.error(f"Failed to parse step data {item}: {e}")
                # Skip malformed steps, but ideally, this indicates a prompt failure.

        if not steps:
            logger.error("No valid steps could be parsed. Returning minimal plan.")
            return ResearchPlan(query, [PlanStep("F0", "Final summary generation (Fallback)", [])], strategy)

        return ResearchPlan(query, steps, raw_data.get("strategy", strategy))

    # --- Default Strategy Implementations (Used as Fallback or for simple cases) ---

    def _default_sequential_planner(self, query: str, context: Optional[Dict[str, Any]]) -> ResearchPlan:
        """A simple, hardcoded sequential plan for robustness."""
        steps = [
            PlanStep(step_id="D1", description=f"Initial broad search for '{query}'", dependencies=[]),
            PlanStep(step_id="D2", description="Filter and rank initial results.", dependencies=["D1"]),
            PlanStep(step_id="D3", description="Deep dive into the top 3 sources.", dependencies=["D2"]),
            PlanStep(step_id="D4", description="Synthesize findings and generate final answer.", dependencies=["D3"]),
        ]
        return ResearchPlan(query, steps, strategy="Sequential (Default Fallback)")

    def _default_parallel_planner(self, query: str, context: Optional[Dict[str, Any]]) -> ResearchPlan:
        """A simple plan suggesting parallel execution paths."""
        steps = [
            PlanStep(step_id="P1", description="Decompose query into two independent sub-problems A and B.", dependencies=[]),
            PlanStep(step_id="PA", description="Execute research path A.", dependencies=["P1"]),
            PlanStep(step_id="PB", description="Execute research path B.", dependencies=["P1"]),
            PlanStep(step_id="PC", description="Merge results from PA and PB.", dependencies=["PA", "PB"]),
        ]
        return ResearchPlan(query, steps, strategy="Parallel (Default Fallback)")

    def _default_tree_based_planner(self, query: str, context: Optional[Dict[str, Any]]) -> ResearchPlan:
        """A simple plan suggesting iterative refinement (Tree-like structure)."""
        steps = [
            PlanStep(step_id="T1", description="Generate initial hypothesis set.", dependencies=[]),
            PlanStep(step_id="T2", description="Test Hypothesis 1.", dependencies=["T1"]),
            PlanStep(step_id="T3", description="Test Hypothesis 2.", dependencies=["T1"]),
            PlanStep(step_id="T4", description="Review results T2/T3. If inconclusive, generate new hypothesis.", dependencies=["T2", "T3"], tool_call="RefineQuery"),
            PlanStep(step_id="T5", description="Final conclusion based on validated hypotheses.", dependencies=["T4"]),
        ]
        return ResearchPlan(query, steps, strategy="Tree-based (Default Fallback)")

    def update_strategy_registry(self, name: str, func: Callable):
        """Allows dynamic registration of new planning functions."""
        self.strategy_registry[name] = func
        logger.info(f"Strategy '{name}' registered.")

# Example Usage (for testing/demonstration, not part of the module's core export)
if __name__ == '__main__':
    # Mock LLM Interface
    class MockLLM:
        def generate_structured_output(self, prompt: str) -> Dict[str, Any]:
            print(f"--- Mock LLM called with prompt snippet: {prompt[:50]} ---")
            return {"strategy": "Mocked", "steps": []}

    mock_llm = MockLLM()
    planner = QueryPlanner(llm_interface=mock_llm)

    try:
        # Test sequential planning (will use mock LLM output structure)
        plan_seq = planner.generate_plan("What is the impact of quantum entanglement on classical cryptography?", strategy="sequential")
        print("\n--- Sequential Plan ---")
        print(plan_seq)
        for step in plan_seq.steps:
            print(f"  {step.step_id}: {step.description} (Deps: {step.dependencies})")

        # Test tree-based planning
        plan_tree = planner.generate_plan("Compare Transformer architectures vs State Space Models.", strategy="tree_based")
        print("\n--- Tree-based Plan ---")
        print(plan_tree)
        for step in plan_tree.steps:
            print(f"  {step.step_id}: {step.description} (Deps: {step.dependencies})")

        # Test unknown strategy
        try:
            planner.generate_plan("Test error handling.", strategy="unknown_strategy")
        except ValueError as e:
            print(f"\nCaught expected error: {e}")

    except Exception as e:
        print(f"An error occurred during example execution: {e}")